version: "3.3"
services:
  ditac:
    build:
      context: .
      args:
        MODEL_REPOSITORY_URI: http://deeplearning.ge.imati.cnr.it
        MODEL_PATH: /ditac/models/
        MODEL_FILENAME: ditac-cable-problem-v0.6-endoftraining.pkl
        FLASK_PORT: 55563
        WEB_PORT: 55564
    env_file:
      - variables.env
    ports:
      - "55563:55563"
      - "55564:55564"
