version: "3.3"
services:
  rclone:
    image: 4ndr3ar/digitbrain-ditac-cnr-cable-problem-ml-model:firstpublicversion
    entrypoint: "/bin/sh -c"
    command: "rclone copy -vv --daemon --dir-cache-time 5s http://deeplearning.ge.imati.cnr.it /ditac/models/ && rclone rcd --rc-web-gui-no-open-browser"
    volumes:
      - type: bind
        source: /data
        target: /data
        bind:
          propagation: rshared
      - /dev/fuse:/dev/fuse
      - /config:/config/rclone
    privileged: true
  ditac:
    build:
      context: .
      args:
        MODEL_REPOSITORY_URI: http://deeplearning.ge.imati.cnr.it
        MODEL_PATH: /ditac/models/
        MODEL_FILENAME: ditac-cable-problem-v0.6-endoftraining.pkl
        FLASK_PORT: 55563
        WEB_PORT: 55564
    env_file:
      - variables.env
    ports:
      - "55563:55563"
      - "55564:55564"
